# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20161110_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hpcjob',
            old_name='status',
            new_name='state',
        ),
        migrations.AddField(
            model_name='hpcjob',
            name='exit_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hpcjob',
            name='job_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hpcjob',
            name='partition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hpcjob',
            name='scale_memGB',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
