# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20161111_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpcjob',
            name='job_wdir',
            field=models.FilePathField(default=None),
            preserve_default=False,
        ),
    ]
