# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_hpcjob_job_wdir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpcjob',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
