# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20161114_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpcjob',
            name='time_limit',
            field=models.IntegerField(null=True),
        ),
    ]
