# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170106_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountactive',
            old_name='account',
            new_name='account_active',
        ),
    ]
