# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170106_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountactive',
            name='account_active',
        ),
        migrations.AddField(
            model_name='accountactive',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='account_active', to='account.Account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountactive',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_active', to=settings.AUTH_USER_MODEL),
        ),
    ]
